# PyTorch Tutorials

# 01 Tensor Basis

In [1]:
import torch

x = torch.empty(2, 2, 2, 3, dtype=torch.int)
print(x)
print(x.dtype)
print(x.size())

tensor([[[[1047687288,        355,          0],
          [         0,        512,        512]],

         [[     29440,    1635072,    8454144],
          [ 123535484,   24904061,     786538]]],


        [[[     65622,    6554225,  326238291],
          [1912602624,         51,      13682]],

         [[   1602048,  410124288, 1912602624],
          [        25,       6770,      54528]]]], dtype=torch.int32)
torch.int32
torch.Size([2, 2, 2, 3])


In [2]:
x= torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
print(torch.add(x,y))
print(y.add_(x))
print(torch.sub(x,y))
print(x.sub_(y))
print(torch.mul(x,y))
print(x.mul_(y))
print(torch.div(x,y))
print(x.div_(y))

tensor([[0.1316, 0.0881],
        [0.3134, 0.8592]])
tensor([[0.7745, 0.3377],
        [0.3128, 0.0061]])
tensor([[0.9061, 0.4258],
        [0.6262, 0.8653]])
tensor([[0.9061, 0.4258],
        [0.6262, 0.8653]])
tensor([[-0.7745, -0.3377],
        [-0.3128, -0.0061]])
tensor([[-0.7745, -0.3377],
        [-0.3128, -0.0061]])
tensor([[-0.7018, -0.1438],
        [-0.1959, -0.0053]])
tensor([[-0.7018, -0.1438],
        [-0.1959, -0.0053]])
tensor([[-0.7745, -0.3377],
        [-0.3128, -0.0061]])
tensor([[-0.7745, -0.3377],
        [-0.3128, -0.0061]])


In [3]:
x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1, :])
print(x[1,1].item())

tensor([[0.5997, 0.1295, 0.8019],
        [0.9433, 0.7782, 0.4380],
        [0.7624, 0.4638, 0.6506],
        [0.5864, 0.8766, 0.5565],
        [0.3984, 0.9545, 0.8698]])
tensor([0.5997, 0.9433, 0.7624, 0.5864, 0.3984])
tensor([0.9433, 0.7782, 0.4380])
0.7782362699508667


In [4]:
x = torch.rand(4,4)
y = x.view(16)
print(y)
y = x.view(-1, 8)
print(y)

tensor([0.9093, 0.8013, 0.7373, 0.0124, 0.0533, 0.4851, 0.2582, 0.9387, 0.8229,
        0.0892, 0.5821, 0.6459, 0.6551, 0.0165, 0.5854, 0.5937])
tensor([[0.9093, 0.8013, 0.7373, 0.0124, 0.0533, 0.4851, 0.2582, 0.9387],
        [0.8229, 0.0892, 0.5821, 0.6459, 0.6551, 0.0165, 0.5854, 0.5937]])


In [5]:
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

a.add_(1)
print(a)
print(b)

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(type(b))

a += 1
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
<class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [6]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  print(z)
  print(z.to("cpu"))
else:
  print("CUDA is not available.")

tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])


In [7]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


# 02 Gradient Calculation With Autograd

In [16]:
x = torch.randn(3, requires_grad = True)
print(x)

y = x+2
print(y)
z = y*y*2
print(z)
z= z.mean()
print(z)

z.backward() # dz/dx
print(x.grad)

tensor([-1.1841,  0.1370, -0.2937], requires_grad=True)
tensor([0.8159, 2.1370, 1.7063], grad_fn=<AddBackward0>)
tensor([1.3315, 9.1331, 5.8226], grad_fn=<MulBackward0>)
tensor(5.4291, grad_fn=<MeanBackward0>)
tensor([1.0879, 2.8493, 2.2750])


In [18]:
x = torch.randn(3, requires_grad = True)
print(x)

y = x+2
print(y)
z = y*y*2
print(z)
# z= z.mean()
print(z)

v = torch.tensor([0.1,1.0,0.001], dtype = torch.float32)
z.backward(v) # dz/dx
print(x.grad)

tensor([ 1.3029, -0.7210, -0.9902], requires_grad=True)
tensor([3.3029, 1.2790, 1.0098], grad_fn=<AddBackward0>)
tensor([21.8188,  3.2717,  2.0392], grad_fn=<MulBackward0>)
tensor([21.8188,  3.2717,  2.0392], grad_fn=<MulBackward0>)
tensor([1.3212e+00, 5.1160e+00, 4.0390e-03])


In [20]:
x = torch.randn(3, requires_grad = True)
print(x)

# x,requires_grad_(False)
# x.detach()
# with torch.no_grad() :

x.requires_grad_(False)
print(x)
y = x.detach()
print(y)
with torch.no_grad():
  y = x + 2
  print(y)

tensor([-0.8342, -0.1007,  0.5341], requires_grad=True)
tensor([-0.8342, -0.1007,  0.5341])
tensor([-0.8342, -0.1007,  0.5341])
tensor([1.1658, 1.8993, 2.5341])


In [26]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
