In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


# 0~29

## introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

NameError: name 'torch' is not defined

In [ ]:
#dim
scalar.ndim

In [ ]:
# get tensor back as python int
scalar.item()

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [ ]:
#matrix
matrix =torch.tensor([[7,8],[9,10]])
matrix

In [ ]:
matrix.ndim

In [ ]:
matrix[1]

In [ ]:
matrix.shape

In [ ]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9,],
                        [2,4,5]]])
tensor

In [ ]:
tensor.ndim

In [ ]:
tensor.shape

In [ ]:
tensor[0]

### Random tensors

In [ ]:
# create a random tensor of size (3,4)

random = torch.rand(3,4)
random

In [ ]:
random.ndim

In [ ]:
# create random tensor with similar shape to an image tensor
rimg = torch.rand(224,224,3)
rimg = torch.rand(size=(224,224,3))
rimg.shape, rimg.ndim

In [ ]:
torch.rand(3,3)

### zeros and ones

In [ ]:
# zeros
zero = torch.zeros(size=(3,4))
zero

In [ ]:
zero*random

In [ ]:
# ones
one = torch.ones(size=(3,4))
one

In [ ]:
one.dtype

### creating a range of tensors and tensors like

In [ ]:
# range
ten = torch.arange(start = 1, end =11, step = 1)
ten

In [ ]:
zeros = torch.zeros_like(input=ten)
zeros

### tensor datatypes

In [ ]:
# float 32
float_32 = torch.tensor([3.0,6.0,9.0], dtype=None,
                        device =None,
                        requires_grad=False)

float_32

In [ ]:
float_32.dtype

In [ ]:
float_16 = float_32.type(torch.float16)
float_16

In [ ]:
float_16*float_32

In [ ]:
int_32 = torch.tensor([3,6,9], dtype=torch.int32)
int_32

In [ ]:
int_32*float_32

### getting information from tensors

1.tensor.dtype
2.tensor.shape
3.tensor.device

In [ ]:
some = torch.rand(3,4)
some

In [ ]:
print(some)
print(f"datatype of tensor: {some.dtype}")
print(f"shape of tensor: {some.shape}")
print(f"device of tensor: {some.device}")

In [ ]:
some.size(), some.shape

### manipulating tensors(tensor operations)
addition
subtraction
multiplication(element-wise)
division
matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 100

In [ ]:
tensor * 10

In [ ]:
tensor - 10

In [ ]:
torch.mul(tensor, 10)

In [ ]:
torch.add(tensor, 10)

### matrix multiplication

1.elemet-wise multiplication
2.matrix multiplication (dot prodoct)

In [ ]:
tensor * tensor

In [ ]:
%%time
torch.matmul(tensor,tensor)

In [ ]:
%%time
torch.dot(tensor, tensor)

In [ ]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

### shape errors

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm(tensor_A, tensor_B)


### transpose

In [ ]:
tensor_B.T

In [ ]:
torch.mm(tensor_A, tensor_B.T)

In [ ]:
print(f"tensor_A shape: {tensor_A.shape}")
print(f"tensor_B shape: {tensor_B.shape}")
print(f"tensor_B.T shape: {tensor_B.T.shape}")
print(f"torch.mm(tensor_A, tensor_B.T) shape: {torch.mm(tensor_A, tensor_B.T).shape}")
print(f"torch.mm(tensor_A, tensor_B.T) shape: {torch.mm(tensor_A, tensor_B.T)}")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(output.shape)

## finding the min max mean sum etc

In [ ]:
x= torch.range(0,100,10, dtype = torch.int32)
x

In [ ]:
torch.min(x), x.min()

In [ ]:
torch.max(x)

In [ ]:
print(x.dtype)

In [ ]:
torch.mean(x)

In [ ]:
torch.mean(x.type(torch.float32))
# x.dtype() is not a function

In [ ]:
torch.sum(x)

In [ ]:
x

In [ ]:
%%time
x.argmin()

In [ ]:
x[1]

In [ ]:
x.argmax()

In [ ]:
print(x[x.argmax()])

## reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
x = torch.arange(1.,10,)
x, x.shape

In [ ]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape
# x*y == size

In [ ]:
z = x.view(1,9)
z, z.shape

In [ ]:
z[:, 0] = 5
z, x

In [ ]:
# stacl

x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

In [ ]:
# squeeze

z.shape

In [ ]:
z.squeeze().shape

In [ ]:
print(f"previous tensor: {z}")
print(f"previous shape: {z.shape}")

z = z.squeeze()
print(f"new tensor: {z}")
print(f"new shape: {z.shape}")

In [ ]:
print(f"previous target: {z}")
print(f"previous shape: {z.shape}")

z = z.unsqueeze(dim=0)
print(f"new target: {z}")
print(f"new shape: {z.shape}")

In [ ]:
x_original = torch.rand(size=(224,224,3)) # h w c

x_permuted = x_original.permute(2, 0, 1) # c h w

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

In [ ]:
x_original[0][0][0]

In [ ]:
x_original[0,0,0]

## indexing with pytorch is similar to indexing with numpy

In [ ]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

In [ ]:
x[0]

In [ ]:
x[0,0]

In [ ]:
x[:, 0]

In [ ]:
x[:, :, 1]

In [ ]:
x[:, 1, 1]

In [ ]:
x[0,0,:]

## pytorch tensors & numpy

In [ ]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

In [ ]:
array.dtype, tensor.dtype

In [ ]:
array = array+ 1
array, tensor

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
numpy_tensor.dtype

In [ ]:
tensor += 1
tensor, numpy_tensor

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

## reproducbility (trying to take random out of random)

random seed

In [ ]:
torch.rand(3,3)

In [ ]:
randon_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(randon_tensor_A)
print(random_tensor_B)
print(randon_tensor_A == random_tensor_B)

In [ ]:
# random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
# torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

In [ ]:
# random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

# 30~32

## running tensors and pytorch objects on the gpu

cuda + nvidia hardware + pytorch

In [ ]:
!nvidia-smi

Wed Aug 28 06:47:47 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

## putting tensors and models on the gpu

In [ ]:
tensor = torch.tensor([1,2,3], device = "cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

## exercises

In [ ]:
torch.rand(7,7)

tensor([[0.3843, 0.1366, 0.9015, 0.9456, 0.1281, 0.1815, 0.0814],
        [0.5219, 0.9975, 0.9766, 0.0553, 0.9551, 0.3575, 0.5134],
        [0.1846, 0.9964, 0.6053, 0.7949, 0.4751, 0.9595, 0.7406],
        [0.4367, 0.5921, 0.6888, 0.0705, 0.9181, 0.2475, 0.4424],
        [0.1462, 0.0136, 0.9792, 0.5117, 0.6998, 0.4410, 0.2610],
        [0.4644, 0.8952, 0.7178, 0.2936, 0.4920, 0.5183, 0.4895],
        [0.3031, 0.2874, 0.1609, 0.5131, 0.7952, 0.3249, 0.2245]])