In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


# 0~29

## introduction to Tensors

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#dim
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [9]:
#matrix
matrix =torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [14]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9,],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [25]:
# create a random tensor of size (3,4)

random = torch.rand(3,4)
random

tensor([[0.1317, 0.9288, 0.4661, 0.9434],
        [0.1186, 0.9487, 0.6335, 0.3079],
        [0.1691, 0.1409, 0.2174, 0.1692]])

In [26]:
random.ndim

2

In [29]:
# create random tensor with similar shape to an image tensor
rimg = torch.rand(224,224,3)
rimg = torch.rand(size=(224,224,3))
rimg.shape, rimg.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
torch.rand(3,3)

tensor([[0.4545, 0.8590, 0.5872],
        [0.3709, 0.1452, 0.4967],
        [0.0064, 0.3253, 0.8094]])

### zeros and ones

In [31]:
# zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zero*random

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
# ones
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
one.dtype

torch.float32

### creating a range of tensors and tensors like

In [43]:
# range
ten = torch.arange(start = 1, end =11, step = 1)
ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
zeros = torch.zeros_like(input=ten)
zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### tensor datatypes

In [124]:
# float 32
float_32 = torch.tensor([3.0,6.0,9.0], dtype=None,
                        device =None,
                        requires_grad=False)

float_32

tensor([3., 6., 9.])

In [46]:
float_32.dtype

torch.float32

In [48]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [49]:
float_16*float_32

tensor([ 9., 36., 81.])

In [50]:
int_32 = torch.tensor([3,6,9], dtype=torch.int32)
int_32

tensor([3, 6, 9], dtype=torch.int32)

In [51]:
int_32*float_32

tensor([ 9., 36., 81.])

### getting information from tensors

1.tensor.dtype
2.tensor.shape
3.tensor.device

In [52]:
some = torch.rand(3,4)
some

tensor([[0.6485, 0.9496, 0.5601, 0.4943],
        [0.6164, 0.7933, 0.1720, 0.6337],
        [0.7821, 0.2104, 0.1622, 0.7623]])

In [53]:
print(some)
print(f"datatype of tensor: {some.dtype}")
print(f"shape of tensor: {some.shape}")
print(f"device of tensor: {some.device}")

tensor([[0.6485, 0.9496, 0.5601, 0.4943],
        [0.6164, 0.7933, 0.1720, 0.6337],
        [0.7821, 0.2104, 0.1622, 0.7623]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device of tensor: cpu


In [54]:
some.size(), some.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

### manipulating tensors(tensor operations)
addition
subtraction
multiplication(element-wise)
division
matrix multiplication

In [56]:
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [57]:
tensor * 10

tensor([10, 20, 30])

In [58]:
tensor - 10

tensor([-9, -8, -7])

In [59]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [60]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### matrix multiplication

1.elemet-wise multiplication
2.matrix multiplication (dot prodoct)

In [62]:
tensor * tensor

tensor([1, 4, 9])

In [72]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 475 µs, sys: 17 µs, total: 492 µs
Wall time: 407 µs


tensor(14)

In [71]:
%%time
torch.dot(tensor, tensor)

CPU times: user 484 µs, sys: 0 ns, total: 484 µs
Wall time: 423 µs


tensor(14)

In [78]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[2.4409, 2.3266, 2.4486],
        [1.4698, 1.1370, 1.2534],
        [2.3373, 2.6717, 2.1332]])

### shape errors

In [80]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### transpose

In [81]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [82]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [86]:
print(f"tensor_A shape: {tensor_A.shape}")
print(f"tensor_B shape: {tensor_B.shape}")
print(f"tensor_B.T shape: {tensor_B.T.shape}")
print(f"torch.mm(tensor_A, tensor_B.T) shape: {torch.mm(tensor_A, tensor_B.T).shape}")
print(f"torch.mm(tensor_A, tensor_B.T) shape: {torch.mm(tensor_A, tensor_B.T)}")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(output.shape)

tensor_A shape: torch.Size([3, 2])
tensor_B shape: torch.Size([3, 2])
tensor_B.T shape: torch.Size([2, 3])
torch.mm(tensor_A, tensor_B.T) shape: torch.Size([3, 3])
torch.mm(tensor_A, tensor_B.T) shape: tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
torch.Size([3, 3])


## finding the min max mean sum etc

In [115]:
x= torch.range(0,100,10, dtype = torch.int32)
x

<ipython-input-115-f2d2d9723717>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x= torch.range(0,100,10, dtype = torch.int32)


tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       dtype=torch.int32)

In [118]:
torch.min(x), x.min()

(tensor(0, dtype=torch.int32), tensor(0, dtype=torch.int32))

In [119]:
torch.max(x)

tensor(100, dtype=torch.int32)

In [116]:
print(x.dtype)

torch.int32


In [117]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Int

In [128]:
torch.mean(x.type(torch.float32))
# x.dtype() is not a function

tensor(50.)

In [129]:
torch.sum(x)

tensor(550)

In [130]:
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       dtype=torch.int32)

In [132]:
%%time
x.argmin()

CPU times: user 393 µs, sys: 0 ns, total: 393 µs
Wall time: 289 µs


tensor(0)

In [133]:
x[1]

tensor(10, dtype=torch.int32)

In [134]:
x.argmax()

tensor(10)

In [135]:
print(x[x.argmax()])

tensor(100, dtype=torch.int32)


## reshaping, stacking, squeezing and unsqueezing tensors

In [146]:
x = torch.arange(1.,10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [147]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape
# x*y == size

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [166]:
z = x.view(1,9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [167]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [168]:
# stacl

x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [169]:
# squeeze

z.shape

torch.Size([1, 9])

In [170]:
z.squeeze().shape

torch.Size([9])

In [171]:
print(f"previous tensor: {z}")
print(f"previous shape: {z.shape}")

z = z.squeeze()
print(f"new tensor: {z}")
print(f"new shape: {z.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])
new tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape: torch.Size([9])


In [172]:
print(f"previous target: {z}")
print(f"previous shape: {z.shape}")

z = z.unsqueeze(dim=0)
print(f"new target: {z}")
print(f"new shape: {z.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])
new target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [173]:
x_original = torch.rand(size=(224,224,3)) # h w c

x_permuted = x_original.permute(2, 0, 1) # c h w

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [174]:
x_original[0][0][0]

tensor(0.4167)

In [176]:
x_original[0,0,0]

tensor(0.4167)

## indexing with pytorch is similar to indexing with numpy

In [177]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [178]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [179]:
x[0,0]

tensor([1, 2, 3])

In [180]:
x[:, 0]

tensor([[1, 2, 3]])

In [183]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [184]:
x[:, 1, 1]

tensor([5])

In [185]:
x[0,0,:]

tensor([1, 2, 3])

## pytorch tensors & numpy

In [214]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [215]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [216]:
array = array+ 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [228]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [229]:
numpy_tensor.dtype

dtype('float32')

In [230]:
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [231]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## reproducbility (trying to take random out of random)

random seed

In [237]:
torch.rand(3,3)

tensor([[0.8404, 0.1066, 0.0602],
        [0.1868, 0.7908, 0.4125],
        [0.3799, 0.9610, 0.2984]])

In [247]:
randon_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(randon_tensor_A)
print(random_tensor_B)
print(randon_tensor_A == random_tensor_B)

tensor([[0.7193, 0.3807, 0.0702, 0.9051],
        [0.9796, 0.7269, 0.6663, 0.6801],
        [0.4874, 0.9313, 0.2637, 0.7847]])
tensor([[0.4497, 0.0708, 0.4389, 0.1247],
        [0.0944, 0.6091, 0.1418, 0.0431],
        [0.1973, 0.2759, 0.9897, 0.4209]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [251]:
# random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
# torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [252]:
# random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# 30~

## running tensors and pytorch objects on the gpu

cuda + nvidia hardware + pytorch